### ISSUE TITLE
Good bye, world.

### ISSUE THREAD

**Issue by ViktorWase** [TheJoggler/hello-world#2]
If one says hello, one must also say farewell.

**Comment by TheJoggler** [comment]
You say goodbye, and I say Hello! Hello, Hello. I don't know why you say goodbye, I say hello.

**Comment by ViktorWase** [comment]
I say high, you say low.

**Comment by ViktorWase** [comment]
You say why, and I say I don't know.

**Comment by ViktorWase** [comment]
Oh no!
